name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Parse json files
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: "Installation of dependencies"
        run: npm ci
      - name: "Parse json files"
        run: npm run test:json
      - name: "Parse json5 files"
        run: npm run test:json5
      - name: "Parse jsonc files"
        run: npm run test:jsonc
